env:
  - GO111MODULE=on

builds:
- env:
    - CGO_ENABLED=0
  binary: git-analyze
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
brews:
  - tap:
      owner: iwata-n
      name: homebrew-git-analyze
    folder: Formula
    homepage: https://github.com/iwata-n/git-analyze
    description: git commit log analyze
    test: |
      system "#{bin}/goreleaser -v"